whisper_model_size: "medium"
whisper_retry_count: 3
whisper_retry_delay: 10
file_directory: "/home/ybaumy/git/whisper-autotranscription/files_download"
remote_directory: "/whisper"
remote_output_directory: "/whisper/output"
swapfile_size: "4096"
swapfile_fallocate: True
swapfile_path: "/swapfile-{{ swapfile_size }}"
swapfile_swappiness: 60
swapfile_vfs_cache_pressure: 100
swapfile_sysctl:
  "vm.swappiness": "{{ swapfile_swappiness }}"
  "vm.vfs_cache_pressure": "{{ swapfile_vfs_cache_pressure }}"
swapfile_delete: False
