---
- name: creates directory
  file:
    path: "{{ remote_output_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0770

- name: get remote hostname
  set_fact:
    remote_hostname: "{{ ansible_hostname }}"

- name: list files remote files in whisper directory
  command: "ls -1 {{ remote_directory }}/{{ remote_hostname }}/"
  register: files

- name: transcribe all audio files
  command: "whisperx {{ remote_directory }}/{{ remote_hostname }}/{{ item }} --model {{ whisper_model_size }} --diarize --hf_token {{ hf_token }} --threads {{ instance_threads }} --output_dir {{ remote_output_directory }} {{ whisper_parameters }}"
  loop: "{{ files.stdout_lines }}"
  async: 2100000
  poll: 5
  register: result
  until: result.finished
  retries: 3
