- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://http.us.debian.org/debian stable main contrib non-free
    state: present

- name: download nvidia cuda keyring
  get_url:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64/cuda-keyring_1.0-1_all.deb"
    dest: /tmp

- name: remove deprecated cuda apt key
  apt_key:
    id: 7fa2af80
    state: absent

- name: install cuda keyring dpkg package
  apt:
    deb: /tmp/cuda-keyring_1.0-1_all.deb

- name: apt update cache
  apt:
    update_cache: yes

- name: install required cuda packages
  apt:
    pkg:
      - nvidia-driver
      - glx-alternative-nvidia
      - nvidia-alternative
      - cuda
      - build-essential
      - dkms
    state: latest
    update_cache: true

- name: install linux kernel headers (did not work with apt module)
  ansible.builtin.shell: "apt install -y linux-headers-$(uname -r)"

- name: reboot the server
  ansible.builtin.reboot:
    post_reboot_delay: 45
    pre_reboot_delay: 0
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
