---
- name: creates directory
  file:
    path: "{{ remote_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0770

- name: Get a list of unique subdirectories
  ansible.builtin.command: find "{{ file_directory }}"/ -maxdepth 2 -mindepth 1 -type d
  register: subdirs
  delegate_to: localhost
  become: false

- name: print subdirs
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ subdirs.stdout_lines }}"

- name: Get remote hostname
  set_fact:
    remote_hostname: "{{ ansible_hostname }}"

- name: print remote_hostname
  ansible.builtin.debug:
    msg: "{{ remote_hostname }}"

- name: upload only the directories matching hostname
  copy:
    src: "{{ item }}"
    dest: "{{ remote_directory }}"
  when: "remote_hostname in item"
  loop: "{{ subdirs.stdout_lines }}"
